<?php 



function prettyauto_menu() {
  $items['prettyauto/autocomplete'] = array(
    'title' => 'Autocomplete taxonomy',
    'page callback' => 'prettyauto_taxonomy_autocomplete',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/prettyauto'] = array(
    'title' => 'Pretty auto',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('prettyauto_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function prettyauto_menu_alter(&$items) {
  if (($key = variable_get('prettyauto_default',''))) {
    // overrides default vocabulary return with a pretty auto 
    $items['taxonomy/autocomplete']['page callback'] = 'prettyauto_taxonomy_autocomplete';
    unset($items['taxonomy/autocomplete']['file']);
    $items['taxonomy/autocomplete']['page arguments'] = array($key, 2 ,3 );
    if( $items['content_taxonomy/autocomplete'])
       $items['content_taxonomy/autocomplete']['page callback'] = 'prettyauto_content_taxonomy_autocomplete_load';
  }
}

function prettyauto_settings() {
  $types  = module_invoke_all('prettyauto');
  $options[''] = 'None';
  foreach ($types as  $type => $trash) {
    $options[$type] = $type;
  }
  $form['prettyauto_default'] = array(
    '#type' => 'select',
    '#title' => 'Default taxonomy autocomplete override',
    '#options'=> $options,
    '#default_value'=> variable_get('prettyauto_default',''),
  );
  return system_settings_form($form);
}



function prettyauto_content_taxonomy_autocomplete_load($field_name, $string = '') {
   // The user enters a comma-separated list of tags. We only autocomplete the last tag.
  // This regexp allows the following types of user input:
  // this, "somecmpany, llc", "and ""this"" w,o.rks", foo bar
  $content_type_info = _content_type_info();
  $vid = $content_type_info['fields'][$field_name]['vid'];
  $tid = content_taxonomy_field_get_parent($content_type_info['fields'][$field_name]);
  $key = variable_get('prettyauto_default','');
  $types = module_invoke_all('prettyauto');
  $info = $types[$key];
  // If the menu system has splitted the search text because of slashes, glue it back.
  if (func_num_args() > 2) {
    $args = func_get_args();
    $string .= '/'. implode('/', array_slice($args, 2));
  }
  
  // The user enters a comma-separated list of tags. We only autocomplete the last tag.
  $array = drupal_explode_tags($string);

  // Fetch last tag
  $last_string = trim(array_pop($array));
  $matches = array();
  if ($last_string != '') {
    if ($tid) {
      $result = db_query_range(db_rewrite_sql("SELECT t.* FROM {term_data} t 
        LEFT JOIN {term_synonym} s ON t.tid = s.tid
        INNER JOIN {term_hierarchy} h ON  t.tid = h.tid
        WHERE h.parent = %d 
        AND (LOWER(t.name) LIKE LOWER('%%%s%%') OR LOWER(s.name) LIKE LOWER('%%%s%%'))", 't', 'tid'),
        $tid,$last_string,$last_string,0,10);
    }
    else {
      $result = db_query_range(db_rewrite_sql("SELECT t.* FROM {term_data} t 
        LEFT JOIN {term_synonym} s ON t.tid = s.tid
        WHERE t.vid = %d 
        AND (LOWER(t.name) LIKE LOWER('%%%s%%') OR LOWER(s.name) LIKE LOWER('%%%s%%'))", 't', 'tid'),
        $vid, $last_string, $last_string, 0, 10);
    }
    $prefix = count($array) ? '"'. implode('", "', $array) .'", ' : '';
    while ($tag = db_fetch_object($result)) {
      $n = $tag->name;
      // Commas and quotes in terms are special cases, so encode 'em.
      if (strpos($tag->name, ',') !== FALSE || strpos($tag->name, '"') !== FALSE) {
        $n = '"'. str_replace('"', '""', $tag->name) .'"';
      }
       if ($info['theme']) $matches[$prefix . $n] = theme($info['theme'],$tag);
      else $matches[$prefix . $n] = check_plain($tag->name) ;
      
      if ($info['link']) $matches[$prefix . $n] .= ' - ' . prettyauto_taxonomy_link($tag);
    }
  }

  drupal_json($matches);
}
function prettyauto_taxonomy_autocomplete($key,$vid, $string = '') {
  // The user enters a comma-separated list of tags. We only autocomplete the last tag.
  static $types;
  if (!isset($types)) {
    $types = module_invoke_all('prettyauto');
  }
  if (empty($types[$key])) {
    include_once(drupal_get_path('module','taxonomy').'/taxonomy.pages.inc');
    return taxonomy_autocomplete($vid,$string);
  }
  $info = $types[$key];
  $array = drupal_explode_tags($string);
  
  $vocabs = explode(" ",$vid);
  // Fetch last tag
  $last_string = trim(array_pop($array));
  $matches = array();
  if ($last_string != '') {
    $args = $vocabs;
    $args[] = $last_string ;
    $limit = variable_get('prettyauto_limit',15);
    $prefix = count($array) ? implode(', ', $array) .', ' : '';
    if ($info['gather'] && function_exists($info['gather'])) {
       $rows = call_user_function($info['gather'],array($vocabs,$string));
    } else {
      
      $result = db_query_range(db_rewrite_sql("SELECT t.* FROM {term_data} t WHERE t.vid in (".db_placeholders($vocabs).") AND LOWER(t.name) LIKE LOWER('%%%s%%')", 't', 'tid'), $args, 0, $limit);
      $rows = array();
    
      while ($tag = db_fetch_object($result)) {
        $rows[] = $tag;
      }     
    }
    if ($limit - count($rows) > 0) drupal_alter('prettyautorows',$rows,$vocabs,$last_string);
    foreach ($rows as $tag) {
      $n = $tag->name;
      // Commas and quotes in terms are special cases, so encode 'em.
      if (strpos($tag->name, ',') !== FALSE || strpos($tag->name, '"') !== FALSE) {
        $n = '"'. str_replace('"', '""', $tag->name) .'"';
      }
      if ($info['theme']) $matches[$prefix . $n] = theme($info['theme'],$tag);
      else $matches[$prefix . $n] = check_plain($tag->name) ;
      
      if ($info['link']) $matches[$prefix . $n] .= ' - ' . prettyauto_taxonomy_link($tag);
    }
    
  }
  drupal_json($matches);
}

function prettyauto_theme() {
  return array(
    'related_terms' => array(
      'arguments' => array('tag' => NULL),
    ),
    'term_description' => array(
      'arguments' => array('tag' => NULL),
    ),
  );
}
function prettyauto_prettyauto() {
  return array(
    'description' => array('theme'=>'term_description', 'link' => TRUE),
    'related_terms' => array('theme'=>'related_terms', 'link' => TRUE)
  );
}
function theme_term_description($tag) {
  if ($tag->description) {
    if (strlen($tag->description) > 35) $tag->description = substr($tag->description,0,35) . '...' ;
    $tag->name .= ' - ' . $tag->description;    
  }
  return $tag->name ;
}
function prettyauto_taxonomy_link($tag) {
  return  l('go',taxonomy_term_path($tag),array('attributes'=>array('class'=>'prettyauto-description','target'=>'_blank')));
}
function theme_related_terms($tag) {
  $relate = taxonomy_get_related($tag->tid);
  $related = array();
  foreach($relate as $rtag) {
    $related[$rtag->vid][] = $rtag->name;
  }
  $vocabs = taxonomy_get_vocabularies();
  $temp = array();
  foreach($related as $vid => $tags) {
    $temp[] = $vocabs[$vid]->name . ': ' .  implode(",",$tags) ; 
  }
  
 
  if (count($temp) > 1) {
    $tag->name .= ' ([' . implode("], [",$temp) . '])';
  } elseif($temp) {
    $tag->name .= ' (' . implode(", ",$temp) . ')';
  }
  return $tag->name;
}